apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-auth-service-deployment
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 5
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeserver
          image: naminsaranga/node
          ports:
            - containerPort: 6060
