name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    with:
      image:sandalisubasinghe95/node
      tag:latest
      registry:docker.io
      username:${{ secrets.DOCKER_USERNAME }}
      password:${{ secrets.DOCKER_PASSWORD }}
      
      

    
